### ISSUE TITLE
Lucrezia SW Developer

### ISSUE THREAD

**Issue by eagletrt** [eagletrt/chimera-telemetria-sender#12]
Per permetterti di lavorare su RPI ti verranno assegnate task che dovrai risolvere dalla sera alla mattina del giorno successivo. Se non porterai a termine le task verrai derisa e buttata fuori dal Team. Buona fortuna

- Familiarizzare con gli script in bash per automatizzare funzioni
- Configurazione di un sistema operativo
- Primo server web che printa hello world
- Continuare con le task

**Comment by euberdeveloper** [comment]
obsolete
